name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - terragrunt/aws/cloud_asset_inventory/src/**
      - images/csp_violation_report_service/app/**
      - .github/workflows/ci_code.yml

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for changes
        uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: filter
        with:
          filters: |
            images/cloud_asset_inventory/sentinel_neo4j_forwarder/src: 'images/cloud_asset_inventory/sentinel_neo4j_forwarder/src/**'
            images/csp_violation_report_service/app: 'images/csp_violation_report_service/app/**'

  tests:
    if: needs.changes.outputs.source != '[]'
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        source: ${{ fromJSON(needs.changes.outputs.source) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dev dependencies
        working-directory: ${{ matrix.source }}
        run: make install-dev

      - name: Install dependencies
        working-directory: ${{ matrix.source }}
        run: make install

      - name: Lint
        working-directory: ${{ matrix.source }}
        run: make lint-ci

      - name: Format
        working-directory: ${{ matrix.source }}
        run: make fmt-ci

      - name: Test
        working-directory: ${{ matrix.source }}
        run: make test
