name: "Terragrunt apply sso proxy"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sso-proxy-terragrunt-apply.yml"
      - "terragrunt/*/sso_proxy/**"
      - "terragrunt/*/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.1.9
  TERRAGRUNT_VERSION: 0.36.7
  TF_INPUT: false
  TF_VAR_pomerium_client_id: ${{ secrets.POMERIUM_CLIENT_ID }}
  TF_VAR_pomerium_client_secret: ${{ secrets.POMERIUM_CLIENT_SECRET }}
  TF_VAR_pomerium_google_client_id: ${{ secrets.POMERIUM_GOOGLE_CLIENT_ID }}
  TF_VAR_pomerium_google_client_secret: ${{ secrets.POMERIUM_GOOGLE_CLIENT_SECRET }}
  TF_VAR_pomerium_sso_credentials: ${{ secrets.POMERIUM_SSO_CREDENTIALS }}
  TF_VAR_session_cookie_secret: ${{ secrets.SESSION_COOKIE_SECRET }}
  TF_VAR_session_key: ${{ secrets.SESSION_KEY }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - uses: cds-snc/paths-filter@v2.10.3
        id: filter
        with:
          filters: |
            sso_proxy:
              - 'terragrunt/aws/sso_proxy/**'
              - 'terragrunt/env/sso_proxy/**'
            common:
              - '.github/workflows/sso-proxy-terragrunt-apply.yml'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/gh_admin_role
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt apply sso proxy
        if: ${{ steps.filter.outputs.sso_proxy == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/sso_proxy"
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
